### ISSUE TITLE
Back | TaskConfig

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/fr-service#15]
#### Config for math task
- [x] **Build nested TaskConfig structure from cofig.yaml** 
   **parameters:**
   - [x] name - name of the exact metric
   - [x] cycle - int value in milles, represents the cycle operating cycle 
   - [x] <del>metrics - map of the named metricss {input1: Value / Fn / Var / Metric, input2: Value / Fn / Var / Metric}</del>
   **key words:**
   - [x] metric name - creates metric with the name "name"
   - [x] let varName - creates named variable
   - [x] fn name - creates function with the "name"
   - [x] const value - creates function input with stored constant "value"
   - [x] <del>point '/path/Point.Name/' - creates function input associated with the data point of path and Point Name </del>

----------
**config example:**
```yaml
task taskName:
   cycle: 100    // ms
   let VarName1:
      input: 
         fn functionName:
            initial: point '/path/Point.Name/'
    
   let VarName2:
      input: 
         fn functionName:
            initial: VarName1
            input: 
               functionName:
                  input1: const someValue
                  input2: point '/path/Point.Name/'
                  input: 
                     fn functionName:
                        input: point '/path/Point.Name/'
...
```
----------
**result example:**
```js
FnConfig { fnType: Var, name: "VarName2", inputs: {
    input: FnConfig { fnType: Fn, name: "functionName", inputs: {
        initial: FnConfig { fnType: Var, name: "VarName2", inputs: {} },
        input: FnConfig { fnType: Fn, name: "functionName", inputs: {
            input: FnConfig { fnType: Fn, name: "functionName", inputs: {
                    input: FnConfig { fnType: Point, name: "/path/Point.Name/", inputs: {} },
            }},
            input2: FnConfig { fnType: Point, name: "/path/Point.Name/", inputs: {} },
            input1: FnConfig { fnType: Const, name: "someValue", inputs: {} },
        }}
    }}
}};
```
