### ISSUE TITLE
Back | MetricConfig

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/fr-service#17]
- [ ] **Build nested MetricConfig structure from cofig.yaml** 
   - [x] ConfigTree + test
   - [x] read ConfigTree + test
      - [x] get as bool + test
      - [x] get as int (i64) + test
      - [x] get as float (f64) + test
      - [x] get as string (&str) + test
   **parameters:**
   - [x] name - name of the exact metric
   - [x] table - target sql table name
   - [x] sql format - sql query formatted like: "UPDATE {table} SET kind = '{input1}' WHERE id = '{input2}';"
   - [x] inputs - map of the named inputs {input1: Value / Fn / Var / Metric, input2: Value / Fn / Var / Metric}
   **key words:**
   - [x] metric name - creates metric conf with the name "name"

----------
**config example:**
```yaml
metric sqlUpdateMetric:
   table: "TableName"
   sql: "UPDATE {table} SET kind = '{input1}' WHERE id = '{input2}';"
   inputs:
      input1: 
         fn functionName:
            initial: VarName1
            input: 
               functionName:
                  input1: const someValue
                  input2: point '/path/Point.Name/'
                  input: 
                     fn functionName:
                        input: point '/path/Point.Name/'
      input2:
         metric sqlSelectMetric:
            table: "TableName"
            sql: "select id from {table} WHERE name = 'metric-name';"
            inputs: {}
...
```
----------
**result example:**
```js
MetricConfig {
    name: "sqlUpdateName",
    table: "TableName",
    sql: "UPDATE {table} SET kind = '{input1}' WHERE id = '{input2}';",
    inputs: {
        input1: FnConfig { fnType: Var, name: "VarName2", inputs: {
            input: FnConfig { fnType: Fn, name: "functionName", inputs: {
                initial: FnConfig { fnType: Var, name: "VarName2", inputs: {} },
                input: FnConfig { fnType: Fn, name: "functionName", inputs: {
                    input: FnConfig { fnType: Fn, name: "functionName", inputs: {
                            input: FnConfig { fnType: Point, name: "/path/Point.Name/", inputs: {} },
                    }},
                    input2: FnConfig { fnType: Point, name: "/path/Point.Name/", inputs: {} },
                    input1: FnConfig { fnType: Const, name: "someValue", inputs: {} },
                }}
            }}
        }},
        input2: MetricConfig {
            name: "sqlSelectMetric",
            table: "TableName",
            sql: "select id from {table} WHERE name = 'metric-name';"
            inputs: {},        
        }
    }
};
```
