### ISSUE TITLE
Back | Queues / Links - map containing queues by there holder name and queue name

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/fr-service#23]
Provides fast distribution of the calculated values into the multiple output queues.
for example:
```yaml
service CmaClient:
    out queue recv-queue:
        max-length: 10000

service ApiClient:
    in queue api-queue:
        max-length: 10000

task task1:
    cycle: 1 ms
    queue: CmaClient.recv-queue
    fn toApiQueue:
        queue: ApiClient.api-queue
        input metric sqlSelectMetric:
            initial: 0.123      # начальное значение
            table: table_name
            sql: "insert into {table} (id, value, timestamp) values ({id}, {input.value}, {input3.timestamp});"
            input1 fn add:
                input1: const float 0.2
                input2: point float '/path/Point.Name'
            input3:
                const int 333
```
