### ISSUE TITLE
Back | MultiQueue

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/fr-service#25]
#### Receives, keeps and publishes data points for all services of the entire application
- [x] receives points into the MPSC queue in the blocking mode
- [x] if new point received, immediately sends it to the all subscribed consumers
- [x] keeps all consumers subscriptions in the single map
- [x] keeps all received points last state stored on the disk

---------
- [x] **MultiQueueConfig**
- [x] **Subscriptions**
- [ ] #32 
- [x] **Service.subscribe(receiverId)** - add method suscribe to the trait Service (returns receiver)
- [x] **Service.unsubscribe(receiverId)** - add method unsuscribe to the trait Service (canceling subscription)
---------
- [ ] Test static subscriptions
   - [x] single sender (broadcast)
   - [x] multiple senders (broadcast)
   - [ ] named subscription (multicast)
- [ ] Test dynamic subscriptions
   - [x] single sender (broadcast)
   - [x] multiple senders (broadcast)
   - [ ] named subscription  (multicast)
---------

```js
{
   "/path/Point.Name1": [
      subscription1,
      ...,
      subscriptionN,
   ],
   ...,
   "/path/Point.NameN": [
      subscription1,
      ...,
      subscriptionN,
   ]
}
```
- [ ] if configured retain mode, all received points will be stored on the local HDD to be loaded after application restart - allows have last known value for data points

#### config example:
```yaml
service MultiQueue:
    in queue in-queue:
        max-length: 10000
    out queue:
        - task1.recv-queue
        - CmaClient.in-queue
        - CmaServer.in-queue

service CmaClient:
    in queue in-queue:
        max-length: 10000
    out queue: MultiQueue.in-queue

service CmaServer:
    in queue in-queue:
        max-length: 10000
    out queue: MultiQueue.in-queue

```
