### ISSUE TITLE
Back | ApiClient

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/fr-service#26]
- [x] Holding single input queue<String>
- [x] Received string messages pops from the queue into the end of local buffer
- [x] Sending messages (wrapped into ApiQuery) from the beginning of the buffer
- [x] Sent messages immediately removed from the buffer
- [ ] #33

config example:
```yaml
service ApiClient:
    in queue api-queue:
        max-length: 10000

task task1:
    cycle: 1 ms
    queue: CmaClient.recv-queue
    fn toApiQueue:
        queue: ApiClient.api-queue
        input metric sqlSelectMetric:
            initial: 0.123      # начальное значение
            table: table_name
            sql: "insert into {table} (id, value, timestamp) values ({id}, {input.value}, {input3.timestamp});"
            input1 fn add:
                input1: const float 0.2
                input2: point float '/path/Point.Name'
            input3:
                const int 333
```
- [x] ApiQuery
- [x] ApiReply
- [x] TcpSocketClientConnect
