### ISSUE TITLE
Back | TcpClient

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/fr-service#27]
- [x] Keeps connection to the CmaServer
- [x] Holding single in queue<String> - points to be sent to the CmaServer
- [x] Holding single out queue<String> - points received from CmaServer

#### TCP Read
- [x] Received from CmaServer points immediately added to the out queue
   _No need buffering in this case, because all data coming from incoming external interfaces passses through all the application without delays and finally accumulating near the outgoing external interfaces, which has buffers_
- [ ] Test

#### TCP Write
- [x] Received from in queue points pops from the queue into the end of local buffer
- [x] Sending points from the beginning of the buffer
- [x] Sent points immediately removed from the buffer
- [x] Test

#### classes
- [x] #37
- [x] #47
- [ ] #33
- [x] #40
- [x] #42 
- [x] #41 

config example:
```yaml
service CmaClient:
    out queue recv-queue:
        max-length: 10000

task task1:
    cycle: 1 ms
    queue: CmaClient.recv-queue
    fn toApiQueue:
        queue: ApiClient.api-queue
        input metric sqlSelectMetric:
            initial: 0.123      # начальное значение
            table: table_name
            sql: "insert into {table} (id, value, timestamp) values ({id}, {input.value}, {input3.timestamp});"
            input1 fn add:
                input1: const float 0.2
                input2: point float '/path/Point.Name'
            input3:
                const int 333
```
