### ISSUE TITLE
Back | Services | points

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/fr-service#61]
#### Returns list of PointConfig
- #60
   - [x] test
- [x] Task.points - returns list of point configurations, that are produced in the Task
   - [x] TaskConfig.points()
      - [x] FnConfig.points() - returning point configs defined just like below:
      ```yaml
          fn toMultiQueue:
              point int CraneMovement.BoomDown: 
                  type: 'Int'
                  offset: 14
                  comment: 'Индикация опускания рукояти'
                  input:
                      const float 0.05
      
      ```
- #51
