### ISSUE TITLE
ConfSubscribe

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/fr-service#76]
#### Service subscribe configuration

The Service to be subscribed on some service / services, by number of criteria's

Following variants of subscriptions supported:
```yaml
# ------------------------------------------------------------------------------------------
subscibe: MultiQueue    # - broadcast suscription to the MultiQueue
# ------------------------------------------------------------------------------------------
subscribe:
    MultiQueue: {}      # - broadcast suscription to the MultiQueue
    AnotherService: {}  # - broadcast suscription to the AnotherService
# ------------------------------------------------------------------------------------------
subscibe: 
    MultiQueue:         # - multicast subscription to the MultiQueue
        Inf: []         #   - on all points having Cot::Inf
subscribe: 
    MultiQueue:                     # - multicast subscription to the MultiQueue
        {cot: Inf, history: r}: []  #   - on all points having Cot::Inf and history::read
# ------------------------------------------------------------------------------------------
subscibe:
    MultiQueue:                         # - multicast subscription to the MultiQueue
        Act: []                         #   - on all points having Cot::Act
        {cot: Inf, history: r}:         #   - on concrete points having Cot::Inf and history::read
            - /App/Service/Point.Name.1
            - /App/Service/Point.Name.2
    AnotherService:                     # - multicast subscription to the AnotherService
        Inf: []                         #   - on all points having Cot::Inf
```
