### ISSUE TITLE
Back | CacheService

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/fr-service#81]
#### Service storing all received events in the memory,
- [x] Storing all received events on the disk if 'retain' option is true
- [x] Subscribe on points by configured criteria
- [x] Storing received points into the HasMap by name as key
- [x] Cyclically delyed stores accumulated changes to the disk if 'retain' option is true

----

Basic configuration parameters:

```yaml
service CacheService Cache:
    retain: true    # true / false - enables storing cache on the disk
    suscribe:
        /App/MultiQueue: []
```
