### ISSUE TITLE
Back | FnConfig

### ISSUE THREAD

**Issue by a-givertzman** [a-givertzman/fr-service#9]
- [x] **Build nested FnConfig structure from cofig.yaml** 

   **key words:**
   - [x] let varName - creates named variable
   - [x] fn name - creates function with the "name"
   - [x] const value - creates function input with stored constant "value"
   - [x] point '/path/Point.Name/' - creates function input associated with the data point of path and Point Name

----------
**config example:**
```yaml
let VarName1:
   input: 
      fn functionName:
         initial: VarName1
         input: 
            functionName:
               input1: const someValue
               input2: point '/path/Point.Name/'
               input: 
                  fn functionName:
                     input: point '/path/Point.Name/'
...
```
----------
**result example:**
```js
FnConfig { fnType: Var, name: "VarName2", inputs: {
    input: FnConfig { fnType: Fn, name: "functionName", inputs: {
        initial: FnConfig { fnType: Var, name: "VarName2", inputs: {} },
        input: FnConfig { fnType: Fn, name: "functionName", inputs: {
            input: FnConfig { fnType: Fn, name: "functionName", inputs: {
                    input: FnConfig { fnType: Point, name: "/path/Point.Name/", inputs: {} },
            }},
            input2: FnConfig { fnType: Point, name: "/path/Point.Name/", inputs: {} },
            input1: FnConfig { fnType: Const, name: "someValue", inputs: {} },
        }}
    }}
}};
```
